FROM ubuntu:20.04

EXPOSE 5000

RUN apt update && apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash && apt install -y nodejs

COPY . .

RUN node -v && npm -v

RUN npm install

RUN REACT_APP_BACKEND_URL=http://127.0.0.1:8000 npm run build

RUN npm install -g serve

CMD serve -s -l 5000 build
